### ISSUE TITLE
Failed to locate digital river I'd on product page

### ISSUE THREAD

**Issue by Edoardo001** [philippnormann/nvidia-sniper#77]
The script gives me this error:" Failed to locate digital river I'd on product page" this is a problem for the correct working fo the script?

**Comment by stewartconnick** [comment]
You're receiving this error due to the fact that nvidia has temporarily removed Founder Edition cards from being sold on their site. If you use their API, there is a null value for the digitalriverID for both the 3080/3090 at the moment and will be updated when they transition back to the nvidia storefront

**Comment by philippnormann** [comment]
Since https://github.com/philippnormann/nvidia-sniper/commit/5f815a016989fa05b8edcf2390f1d310670a202c we use pre-cached product IDs, which solves this issue.
